#NAME: Jonathan Liau
#EMAIL: jonathanl1108@g.ucla.edu
#ID: 105182103

dist: connected.png copy.png build_run.png git.png Makefile README
	tar -czvf lab4a-105182103.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README
