#NAME: Jonathan Liau
#EMAIL: jonathanl1108@g.ucla.edu
#ID: 105182103

lab0:
	gcc -Wall -Wextra -g -o lab1a lab1a.c;
clean:
	rm -rf lab1a *.tar.gz *.txt
dist:
	tar -czvf lab1a-105182103.tar.gz lab1a.c Makefile \
	README

