# NAME: Jonathan Liau
# EMAIL: jonathanl1108@g.ucla.edu
# ID: 105182103
lab3b: 
	rm -f lab3b
	ln run_lab3b lab3b
	chmod u+x lab3b
clean:
	rm -f lab3b-105182103.tar.gz lab3b
dist:
	tar -czvf lab3b-105182103.tar.gz lab3b.py run_lab3b README Makefile
