#NAME: Jonathan Liau
#EMAIL: jonathanl1108@g.ucla.edu
#ID: 105182103

lab1b:
	gcc -Wall -Wextra -lz -g -o lab1b-client lab1b-client.c
	gcc -Wall -Wextra -lz -g -o lab1b-server lab1b-server.c
clean:
	rm -rf  lab1b-client  lab1b-server *.tar.gz *.txt
dist:
	tar -czvf lab1b-105182103.tar.gz lab1b-client.c lab1b-server.c Makefile README 

