#NAME: Jonathan Liau
#EMAIL: jonathanliau747@gmail.com
#ID: 105182103
build:
	gcc -o lab4b -g -lm -lmraa -Wall -Wextra lab4b.c
clean: 
	rm -f lab4b lab4b-105182103.tar.gz
dist: 
	tar -czvf lab4b-105182103.tar.gz lab4b.c Makefile README check.sh
check:
	chmod +x check.sh
	./check.sh


